DROP TABLE DENSO.DNKR_AUTH_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_AUTH_DETAIL
(
  AUTH_CODE  VARCHAR2(45 BYTE),
  AUTH_NUM   NUMBER                             DEFAULT 0,
  MCD_CODE   VARCHAR2(45 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_AUTH_DETAIL.AUTH_CODE IS '권한코드';

COMMENT ON COLUMN DENSO.DNKR_AUTH_DETAIL.AUTH_NUM IS '권한(숫자,비트연산으로 권환확인)';

COMMENT ON COLUMN DENSO.DNKR_AUTH_DETAIL.MCD_CODE IS '메뉴코드';


ALTER TABLE DENSO.DNKR_AUTH_DETAIL ADD (
  CONSTRAINT DNKR_AUTH_DETAIL_FK1 
  FOREIGN KEY (AUTH_CODE) 
  REFERENCES DENSO.DNKR_AUTH_CODE (AUTH_CODE)
  ENABLE VALIDATE);