ALTER TABLE DENSO.DNKR_RELATION_LOCATION
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_RELATION_LOCATION CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_RELATION_LOCATION
(
  LOC_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  LOC_USE   CHAR(1 BYTE)                        DEFAULT 'Y',
  CLS_CODE  VARCHAR2(45 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_RELATION_LOCATION.LOC_CODE IS '사업장코드';

COMMENT ON COLUMN DENSO.DNKR_RELATION_LOCATION.LOC_USE IS '사용여부(Y,N)';

COMMENT ON COLUMN DENSO.DNKR_RELATION_LOCATION.CLS_CODE IS '상위사업부코드';


CREATE UNIQUE INDEX DENSO.DRM_RELATION_LOCATION_PK ON DENSO.DNKR_RELATION_LOCATION
(LOC_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_RELATION_LOCATION ADD (
  CONSTRAINT DNKR_RELATION_LOCATION_PK
  PRIMARY KEY
  (LOC_CODE)
  USING INDEX DENSO.DRM_RELATION_LOCATION_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_RELATION_LOCATION ADD (
  CONSTRAINT DNKR_RELATION_LOCATION_FK1 
  FOREIGN KEY (CLS_CODE) 
  REFERENCES DENSO.DNKR_RELATION_CLASS (CLS_CODE)
  ENABLE VALIDATE);