ALTER TABLE DENSO.DNKR_BOARD_FILES
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_BOARD_FILES CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_BOARD_FILES
(
  BRD_FILE_CODE  NUMBER                         NOT NULL,
  BRD_CODE       NUMBER                         NOT NULL,
  BRD_ORG_NAME   VARCHAR2(100 BYTE)             NOT NULL,
  BRD_SAVE_NAME  VARCHAR2(100 BYTE)             NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_BOARD_FILES.BRD_FILE_CODE IS '첨부파일코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD_FILES.BRD_CODE IS '게시물코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD_FILES.BRD_ORG_NAME IS '원본파일명';

COMMENT ON COLUMN DENSO.DNKR_BOARD_FILES.BRD_SAVE_NAME IS '저장된파일명';


CREATE UNIQUE INDEX DENSO.DRM_BOARD_FILES_PK ON DENSO.DNKR_BOARD_FILES
(BRD_FILE_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_BOARD_FILES ADD (
  CONSTRAINT DNKR_BOARD_FILES_PK
  PRIMARY KEY
  (BRD_FILE_CODE)
  USING INDEX DENSO.DRM_BOARD_FILES_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_BOARD_FILES ADD (
  CONSTRAINT DNKR_BOARD_FILES_FK1 
  FOREIGN KEY (BRD_CODE) 
  REFERENCES DENSO.DNKR_BOARD (BRD_CODE)
  ENABLE VALIDATE);