CREATE TABLE TB_CM_USER_ROLE (
  USER_ID         NUMBER(20) NOT NULL,
  ROLE_CD         VARCHAR2(50) NOT NULL,
  RGSTR_ID        NUMBER(20) NOT NULL,
  RGST_DT         TIMESTAMP NOT NULL,
  UPDTR_ID        NUMBER(20) NOT NULL,
  UPDT_DT         TIMESTAMP NOT NULL,
  CONSTRAINT PK_CM_USER_ROLE
  UNIQUE (USER_ID, ROLE_CD)
)
/
COMMENT ON TABLE TB_CM_USER_ROLE IS '사용자역할'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.USER_ID IS '사용자ID'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.ROLE_CD IS 'ROLE_CD'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.RGSTR_ID IS '등록자ID'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.RGST_DT IS '등록일시'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.UPDTR_ID IS '수정일시'
/
COMMENT ON COLUMN TB_CM_USER_ROLE.UPDT_DT IS '수정일시'
/

