DROP TABLE DENSO.DNKR_SURVEY_DES_RESULT CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_SURVEY_DES_RESULT
(
  QST_CODE    VARCHAR2(45 BYTE)                 NOT NULL,
  EMP_NUMBER  VARCHAR2(45 BYTE),
  DR_ANSWER   CLOB,
  SRV_CODE    VARCHAR2(45 BYTE)                 NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_SURVEY_DES_RESULT.QST_CODE IS '문항코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_DES_RESULT.EMP_NUMBER IS '사원번호';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_DES_RESULT.DR_ANSWER IS '답변';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_DES_RESULT.SRV_CODE IS '설문지코드';


ALTER TABLE DENSO.DNKR_SURVEY_DES_RESULT ADD (
  CONSTRAINT DNKR_SURVEY_DES_RESULT_FK1 
  FOREIGN KEY (SRV_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_CODE (SRV_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_SURVEY_DES_RESULT_FK2 
  FOREIGN KEY (EMP_NUMBER) 
  REFERENCES DENSO.DNKR_EMP (EMP_NUMBER)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_SURVEY_DES_RESULT_FK3 
  FOREIGN KEY (QST_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_QUESTION (QST_CODE)
  ENABLE VALIDATE);