DROP TABLE DENSO.DNKR_BOARD_NM CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_BOARD_NM
(
  BRD_CODE     NUMBER,
  CMC_CODE     VARCHAR2(45 BYTE),
  BRD_TITLE    VARCHAR2(20 BYTE),
  BRD_CONTENT  VARCHAR2(20 BYTE),
  BRD_WRITER   VARCHAR2(45 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_BOARD_NM.BRD_CODE IS '게시물코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD_NM.CMC_CODE IS '언어코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD_NM.BRD_TITLE IS '타이틀';

COMMENT ON COLUMN DENSO.DNKR_BOARD_NM.BRD_CONTENT IS '내용';

COMMENT ON COLUMN DENSO.DNKR_BOARD_NM.BRD_WRITER IS '작성자';


ALTER TABLE DENSO.DNKR_BOARD_NM ADD (
  CONSTRAINT DNKR_BOARD_NM_FK1 
  FOREIGN KEY (BRD_CODE) 
  REFERENCES DENSO.DNKR_BOARD (BRD_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_BOARD_NM_FK2 
  FOREIGN KEY (CMC_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE);