ALTER TABLE DENSO.DNKR_EMP
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_EMP CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_EMP
(
  EMP_NUMBER        VARCHAR2(10 BYTE)           NOT NULL,
  CLS_CODE          VARCHAR2(45 BYTE),
  LOC_CODE          VARCHAR2(45 BYTE),
  TEAM_CODE         VARCHAR2(45 BYTE),
  AUTH_CODE         VARCHAR2(45 BYTE),
  EMP_NAME          VARCHAR2(40 BYTE),
  EMP_EMAIL         VARCHAR2(100 BYTE),
  EMP_ID            VARCHAR2(20 BYTE),
  EMP_SYNC_DATE     DATE,
  EMP_USE           CHAR(1 BYTE)                DEFAULT 'Y'                   NOT NULL,
  EMP_PWD           VARCHAR2(45 BYTE),
  EMP_PRIVATE_AUTH  CHAR(1 BYTE)                DEFAULT 'N'                   NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_NUMBER IS '사번';

COMMENT ON COLUMN DENSO.DNKR_EMP.CLS_CODE IS '사업부코드';

COMMENT ON COLUMN DENSO.DNKR_EMP.LOC_CODE IS '사업장코드';

COMMENT ON COLUMN DENSO.DNKR_EMP.TEAM_CODE IS '부서(팀)코드';

COMMENT ON COLUMN DENSO.DNKR_EMP.AUTH_CODE IS '공통권한코드';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_NAME IS '사원명';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_EMAIL IS '이메일';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_ID IS '아이디';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_SYNC_DATE IS '원본데이터 동기화 일자';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_USE IS '사용여부(Y,N)';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_PWD IS '패스워드';

COMMENT ON COLUMN DENSO.DNKR_EMP.EMP_PRIVATE_AUTH IS '개인권한사용여부(Y,N)';


CREATE UNIQUE INDEX DENSO.DRM_EMP_PK ON DENSO.DNKR_EMP
(EMP_NUMBER)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_EMP ADD (
  CONSTRAINT DNKR_EMP_PK
  PRIMARY KEY
  (EMP_NUMBER)
  USING INDEX DENSO.DRM_EMP_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_EMP ADD (
  CONSTRAINT DNKR_EMP_FK1 
  FOREIGN KEY (CLS_CODE) 
  REFERENCES DENSO.DNKR_RELATION_CLASS (CLS_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_EMP_FK2 
  FOREIGN KEY (LOC_CODE) 
  REFERENCES DENSO.DNKR_RELATION_LOCATION (LOC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_EMP_FK3 
  FOREIGN KEY (TEAM_CODE) 
  REFERENCES DENSO.DNKR_RELATION_TEAM (TEAM_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_EMP_FK4 
  FOREIGN KEY (AUTH_CODE) 
  REFERENCES DENSO.DNKR_AUTH_CODE (AUTH_CODE)
  ENABLE VALIDATE);