ALTER TABLE DENSO.NOTICE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.NOTICE CASCADE CONSTRAINTS;

CREATE TABLE DENSO.NOTICE
(
  NOTICE_NO         VARCHAR2(5 BYTE)            NOT NULL,
  LANGUAGE          VARCHAR2(2 BYTE)            NOT NULL,
  TITLE             VARCHAR2(50 CHAR)           NOT NULL,
  NOTICE            VARCHAR2(250 CHAR)          NOT NULL,
  HIGHLIGHT_FLAG    VARCHAR2(1 BYTE),
  NEW_FLAG          VARCHAR2(1 BYTE),
  PUBLICATION_DATE  DATE,
  ORDER_NUMBER      NUMBER(5),
  CREATE_USER       VARCHAR2(20 BYTE)           NOT NULL,
  CREATE_DATE       TIMESTAMP(3)                NOT NULL,
  LAST_UPDATE_USER  VARCHAR2(20 BYTE)           NOT NULL,
  LAST_UPDATE_DATE  TIMESTAMP(3)                NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE DENSO.NOTICE IS 'Notice';

COMMENT ON COLUMN DENSO.NOTICE.NOTICE_NO IS 'Notice number';

COMMENT ON COLUMN DENSO.NOTICE.LANGUAGE IS 'Language';

COMMENT ON COLUMN DENSO.NOTICE.TITLE IS 'Notice title';

COMMENT ON COLUMN DENSO.NOTICE.NOTICE IS 'Notice';

COMMENT ON COLUMN DENSO.NOTICE.HIGHLIGHT_FLAG IS 'Highlight flag';

COMMENT ON COLUMN DENSO.NOTICE.NEW_FLAG IS 'New flag';

COMMENT ON COLUMN DENSO.NOTICE.PUBLICATION_DATE IS 'Publication date';

COMMENT ON COLUMN DENSO.NOTICE.ORDER_NUMBER IS 'Order number for sorting';

COMMENT ON COLUMN DENSO.NOTICE.CREATE_USER IS 'First created by';

COMMENT ON COLUMN DENSO.NOTICE.CREATE_DATE IS 'First created date';

COMMENT ON COLUMN DENSO.NOTICE.LAST_UPDATE_USER IS 'Last updated by';

COMMENT ON COLUMN DENSO.NOTICE.LAST_UPDATE_DATE IS 'Last updated date';


CREATE UNIQUE INDEX DENSO.NOTICE_PK ON DENSO.NOTICE
(NOTICE_NO, LANGUAGE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.NOTICE ADD (
  CONSTRAINT NOTICE_PK
  PRIMARY KEY
  (NOTICE_NO, LANGUAGE)
  USING INDEX DENSO.NOTICE_PK
  ENABLE VALIDATE);