CREATE TABLE TB_CM_USER (
  USER_ID     NUMBER(20) NOT NULL,
  RGSTR_ID    NUMBER(20) NOT NULL,
  RGST_DT     TIMESTAMP  NOT NULL,
  UPDTR_ID    NUMBER(20) NOT NULL,
  UPDT_DT     TIMESTAMP  NOT NULL,
  ACCT_ID     VARCHAR(20) NOT NULL,
  ACCT_PW     VARCHAR(20) NOT NULL,
  EMAIL       VARCHAR(255) NOT NULL,
  TEL_NO      VARCHAR(20) NULL,
  MOBLPHON_NO VARCHAR(20) NULL,
  FST_NM      VARCHAR(30) NOT NULL,
  MDL_NM      VARCHAR(30),
  LST_NM      VARCHAR(30) NOT NULL,
  USE_YN      VARCHAR(1) DEFAULT 'Y'
  CONSTRAINT PK_CM_USER
  UNIQUE (USER_ID)
)
/
COMMENT ON TABLE TB_CM_USER IS '사용자'
/
COMMENT ON COLUMN TB_CM_USER.USER_ID IS '사용자ID'
/
COMMENT ON COLUMN TB_CM_USER.RGSTR_ID IS '등록자ID'
/
COMMENT ON COLUMN TB_CM_USER.RGST_DT IS '등록일시'
/
COMMENT ON COLUMN TB_CM_USER.UPDTR_ID IS '수정자ID'
/
COMMENT ON COLUMN TB_CM_USER.UPDT_DT IS '수정일시'
/
COMMENT ON COLUMN TB_CM_USER.ACCT_ID IS 'ACCOUNT_ID'
/
COMMENT ON COLUMN TB_CM_USER.ACCT_PW IS 'ACCOUNT_PASSWORD'
/
COMMENT ON COLUMN TB_CM_USER.EMAIL IS '이메일'
/
COMMENT ON COLUMN TB_CM_USER.TEL_NO IS '전화번호'
/
COMMENT ON COLUMN TB_CM_USER.MOBLPHON_NO IS '휴대폰번호'
/
COMMENT ON COLUMN TB_CM_USER.FST_NM IS '이름'
/
COMMENT ON COLUMN TB_CM_USER.MDL_NM IS '중간이름'
/
COMMENT ON COLUMN TB_CM_USER.LST_NM IS '성'
/
COMMENT ON COLUMN TB_CM_USE.USE_YN IS '사용여부'