DROP TABLE DENSO.DNKR_PRIVATE_AUTH CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_PRIVATE_AUTH
(
  EMP_NUMBER  VARCHAR2(10 BYTE)                 NOT NULL,
  MCD_CODE    VARCHAR2(45 BYTE)                 NOT NULL,
  AUTH_NUM    NUMBER                            DEFAULT 0
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_PRIVATE_AUTH.EMP_NUMBER IS '사번';

COMMENT ON COLUMN DENSO.DNKR_PRIVATE_AUTH.MCD_CODE IS '메뉴코드';

COMMENT ON COLUMN DENSO.DNKR_PRIVATE_AUTH.AUTH_NUM IS '권한(숫자,비트연산으로 권한확인)';


ALTER TABLE DENSO.DNKR_PRIVATE_AUTH ADD (
  CONSTRAINT DRM_PRIVATE_AUTH_FK1 
  FOREIGN KEY (EMP_NUMBER) 
  REFERENCES DENSO.DNKR_EMP (EMP_NUMBER)
  ENABLE VALIDATE);