ALTER TABLE DENSO.DNKR_RELATION_CLASS
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_RELATION_CLASS CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_RELATION_CLASS
(
  CLS_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  CLS_USE   VARCHAR2(1 BYTE)                    DEFAULT 'Y'
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_RELATION_CLASS.CLS_CODE IS '사업부코드';

COMMENT ON COLUMN DENSO.DNKR_RELATION_CLASS.CLS_USE IS '사용여부(Y,N)';


CREATE UNIQUE INDEX DENSO.DRM_RELATION_CLASS_PK ON DENSO.DNKR_RELATION_CLASS
(CLS_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_RELATION_CLASS ADD (
  CONSTRAINT DNKR_RELATION_CLASS_PK
  PRIMARY KEY
  (CLS_CODE)
  USING INDEX DENSO.DRM_RELATION_CLASS_PK
  ENABLE VALIDATE);