ALTER TABLE DENSO.DNKR_SURVEY_QUESTION
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_SURVEY_QUESTION CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_SURVEY_QUESTION
(
  QST_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  SRV_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  QST_TYPE  VARCHAR2(10 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_SURVEY_QUESTION.QST_CODE IS '질문코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_QUESTION.SRV_CODE IS '설문지코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_QUESTION.QST_TYPE IS '질문타입(radio,checkbox,text)';


CREATE UNIQUE INDEX DENSO.DRM_SURYVEY_QUESTION_PK ON DENSO.DNKR_SURVEY_QUESTION
(QST_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_SURVEY_QUESTION ADD (
  CONSTRAINT DNKR_SURYVEY_QUESTION_PK
  PRIMARY KEY
  (QST_CODE)
  USING INDEX DENSO.DRM_SURYVEY_QUESTION_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_SURVEY_QUESTION ADD (
  CONSTRAINT DNKR_SURYVEY_QUESTION_FK1 
  FOREIGN KEY (SRV_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_CODE (SRV_CODE)
  ENABLE VALIDATE);