DROP TABLE DENSO.DNKR_MENU_CODE_NM CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_MENU_CODE_NM
(
  MCD_CODE  NUMBER                              NOT NULL,
  CMC_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  MCD_NAME  VARCHAR2(100 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE_NM.MCD_CODE IS '메뉴코드';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE_NM.CMC_CODE IS '언어코드';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE_NM.MCD_NAME IS '메뉴명칭';


ALTER TABLE DENSO.DNKR_MENU_CODE_NM ADD (
  CONSTRAINT DNKR_MENU_CODE_NM_FK1 
  FOREIGN KEY (CMC_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_MENU_CODE_NM_FK2 
  FOREIGN KEY (MCD_CODE) 
  REFERENCES DENSO.DNKR_MENU_CODE (MCD_CODE)
  ENABLE VALIDATE);