ALTER TABLE DENSO.DNKR_BOARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_BOARD CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_BOARD
(
  BRD_CODE    NUMBER                            NOT NULL,
  EMP_NUMBER  VARCHAR2(10 BYTE),
  BRD_DATE    DATE,
  BRD_PWD     VARCHAR2(40 BYTE),
  BRD_REF     NUMBER                            DEFAULT 0,
  BRD_STEP    NUMBER                            DEFAULT 0,
  BRD_LEVEL   NUMBER                            DEFAULT 0
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_CODE IS '게시물코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD.EMP_NUMBER IS '사번';

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_DATE IS '작성일자';

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_PWD IS '패스워드';

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_REF IS '부모글코드';

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_STEP IS '답변글 깊이';

COMMENT ON COLUMN DENSO.DNKR_BOARD.BRD_LEVEL IS '답변글 순서';


CREATE UNIQUE INDEX DENSO.DRM_BOARD_PK ON DENSO.DNKR_BOARD
(BRD_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_BOARD ADD (
  CONSTRAINT DNKR_BOARD_PK
  PRIMARY KEY
  (BRD_CODE)
  USING INDEX DENSO.DRM_BOARD_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_BOARD ADD (
  CONSTRAINT DNKR_BOARD_FK1 
  FOREIGN KEY (EMP_NUMBER) 
  REFERENCES DENSO.DNKR_EMP (EMP_NUMBER)
  ENABLE VALIDATE);