ALTER TABLE DENSO.DEPT_INFO
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DEPT_INFO CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DEPT_INFO
(
  DEPT_NO           VARCHAR2(2 BYTE)            NOT NULL,
  LANGUAGE          VARCHAR2(2 BYTE)            NOT NULL,
  DEPT_NAME         VARCHAR2(50 BYTE)           NOT NULL,
  CREATE_USER       VARCHAR2(20 BYTE)           NOT NULL,
  CREATE_DATE       TIMESTAMP(3)                NOT NULL,
  LAST_UPDATE_USER  VARCHAR2(20 BYTE)           NOT NULL,
  LAST_UPDATE_DATE  TIMESTAMP(3)                NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON TABLE DENSO.DEPT_INFO IS 'Department information';

COMMENT ON COLUMN DENSO.DEPT_INFO.DEPT_NO IS 'Department number';

COMMENT ON COLUMN DENSO.DEPT_INFO.LANGUAGE IS 'Language';

COMMENT ON COLUMN DENSO.DEPT_INFO.DEPT_NAME IS 'Department name';

COMMENT ON COLUMN DENSO.DEPT_INFO.CREATE_USER IS 'First created by';

COMMENT ON COLUMN DENSO.DEPT_INFO.CREATE_DATE IS 'First created date';

COMMENT ON COLUMN DENSO.DEPT_INFO.LAST_UPDATE_USER IS 'Last updated by';

COMMENT ON COLUMN DENSO.DEPT_INFO.LAST_UPDATE_DATE IS 'Last updated date';


CREATE UNIQUE INDEX DENSO.DEPT_INFO_PK ON DENSO.DEPT_INFO
(DEPT_NO, LANGUAGE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DEPT_INFO ADD (
  CONSTRAINT DEPT_INFO_PK
  PRIMARY KEY
  (DEPT_NO, LANGUAGE)
  USING INDEX DENSO.DEPT_INFO_PK
  ENABLE VALIDATE);