DROP TABLE DENSO.DNKR_SURVEY_TARGET CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_SURVEY_TARGET
(
  SRV_CODE           VARCHAR2(45 BYTE),
  EMP_NUMBER         VARCHAR2(10 BYTE),
  EMP_EMAIL          VARCHAR2(100 BYTE),
  TGT_PARTICIPATION  CHAR(1 BYTE)               DEFAULT 'N'
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_SURVEY_TARGET.SRV_CODE IS '설문지코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_TARGET.EMP_NUMBER IS '사원번호';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_TARGET.EMP_EMAIL IS '이메일';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_TARGET.TGT_PARTICIPATION IS '참여여부(N,Y)';


ALTER TABLE DENSO.DNKR_SURVEY_TARGET ADD (
  CONSTRAINT DNKR_SURVEY_TARGET_FK1 
  FOREIGN KEY (SRV_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_CODE (SRV_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_SURVEY_TARGET_FK2 
  FOREIGN KEY (EMP_NUMBER) 
  REFERENCES DENSO.DNKR_EMP (EMP_NUMBER)
  ENABLE VALIDATE);