DROP TABLE DENSO.DNKR_COMMON_CODE_NM CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_COMMON_CODE_NM
(
  CMC_CODE         VARCHAR2(45 BYTE),
  CNM_LANG_CODE    VARCHAR2(45 BYTE),
  CNM_NAME         VARCHAR2(100 BYTE),
  CNM_DESCRIPTION  VARCHAR2(200 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE_NM.CMC_CODE IS '코드번호';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE_NM.CNM_LANG_CODE IS '언어코드';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE_NM.CNM_NAME IS '코드명칭';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE_NM.CNM_DESCRIPTION IS '코드설명';


ALTER TABLE DENSO.DNKR_COMMON_CODE_NM ADD (
  CONSTRAINT DNKR_COMMON_CODE_NM_FK1 
  FOREIGN KEY (CMC_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_COMMON_CODE_NM_FK2 
  FOREIGN KEY (CNM_LANG_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE);