ALTER TABLE DENSO.DNKR_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_LOG CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_LOG
(
  LOG_IDX     NUMBER                            NOT NULL,
  LOG_ID      VARCHAR2(20 BYTE),
  LOG_URI     VARCHAR2(200 BYTE),
  LOG_DATE    DATE,
  MCD_CODE    VARCHAR2(45 BYTE),
  LOG_IP      VARCHAR2(45 BYTE),
  EMP_NUMBER  VARCHAR2(10 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_LOG.LOG_IDX IS '로그코드';

COMMENT ON COLUMN DENSO.DNKR_LOG.LOG_ID IS '대상자ID';

COMMENT ON COLUMN DENSO.DNKR_LOG.LOG_URI IS '접근URL';

COMMENT ON COLUMN DENSO.DNKR_LOG.LOG_DATE IS '접근일자';

COMMENT ON COLUMN DENSO.DNKR_LOG.MCD_CODE IS '접근메뉴코드';

COMMENT ON COLUMN DENSO.DNKR_LOG.LOG_IP IS '접근IP';

COMMENT ON COLUMN DENSO.DNKR_LOG.EMP_NUMBER IS '사원번호';


CREATE UNIQUE INDEX DENSO.DRM_LOG_PK ON DENSO.DNKR_LOG
(LOG_IDX)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_LOG ADD (
  CONSTRAINT DNKR_LOG_PK
  PRIMARY KEY
  (LOG_IDX)
  USING INDEX DENSO.DRM_LOG_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_LOG ADD (
  CONSTRAINT DNKR_LOG_FK1 
  FOREIGN KEY (EMP_NUMBER) 
  REFERENCES DENSO.DNKR_EMP (EMP_NUMBER)
  ENABLE VALIDATE);