ALTER TABLE DENSO.DNKR_COMMON_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_COMMON_CODE CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_COMMON_CODE
(
  CMC_CODE         VARCHAR2(45 BYTE)            NOT NULL,
  CMC_PARENT_CODE  VARCHAR2(45 BYTE),
  CMC_REGDATE      DATE,
  CMC_USE_YN       CHAR(1 BYTE)                 DEFAULT 'Y'                   NOT NULL,
  CMC_TYPE         VARCHAR2(4 BYTE)             DEFAULT 'MAIN'                NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE.CMC_CODE IS '코드번호';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE.CMC_PARENT_CODE IS '부모코드번호';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE.CMC_REGDATE IS '변경일자';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE.CMC_USE_YN IS '코드사용여부(Y,N)';

COMMENT ON COLUMN DENSO.DNKR_COMMON_CODE.CMC_TYPE IS '코드유형(MAIN,SUB)';


CREATE UNIQUE INDEX DENSO.DRM_COMMON_CODE_PK ON DENSO.DNKR_COMMON_CODE
(CMC_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_COMMON_CODE ADD (
  CONSTRAINT DNKR_TYPE_CHECK
  CHECK (CMC_TYPE IN('MAIN', 'SUB'))
  ENABLE VALIDATE,
  CONSTRAINT DNKR_USE_YN_CHECK
  CHECK (CMC_USE_YN IN('Y', 'N'))
  ENABLE VALIDATE,
  CONSTRAINT DNKR_COMMON_CODE_PK
  PRIMARY KEY
  (CMC_CODE)
  USING INDEX DENSO.DRM_COMMON_CODE_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_COMMON_CODE ADD (
  CONSTRAINT DNKR_COMMON_CODE_FK1 
  FOREIGN KEY (CMC_PARENT_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE);