DROP TABLE DENSO.DNKR_AUTH_CODE_NM CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_AUTH_CODE_NM
(
  CMC_CODE          VARCHAR2(45 BYTE),
  AUTH_CODE         VARCHAR2(45 BYTE),
  AUTH_NAME         VARCHAR2(100 BYTE),
  AUTH_DESCRIPTION  VARCHAR2(200 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE_NM.CMC_CODE IS '언어코드';

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE_NM.AUTH_CODE IS '권한코드';

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE_NM.AUTH_NAME IS '권한명칭';

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE_NM.AUTH_DESCRIPTION IS '권한설명';


ALTER TABLE DENSO.DNKR_AUTH_CODE_NM ADD (
  CONSTRAINT DNKR_AUTH_CODE_NM_FK1 
  FOREIGN KEY (AUTH_CODE) 
  REFERENCES DENSO.DNKR_AUTH_CODE (AUTH_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_AUTH_CODE_NM_FK2 
  FOREIGN KEY (CMC_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE);