ALTER TABLE DENSO.DNKR_RELATION_NM
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_RELATION_NM CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_RELATION_NM
(
  CMC_CODE  VARCHAR2(45 BYTE),
  REL_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  REL_NAME  VARCHAR2(100 BYTE)
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_RELATION_NM.CMC_CODE IS '언어코드';

COMMENT ON COLUMN DENSO.DNKR_RELATION_NM.REL_CODE IS '조직도코드(사업부,사업장,부서)';

COMMENT ON COLUMN DENSO.DNKR_RELATION_NM.REL_NAME IS '명칭';


CREATE UNIQUE INDEX DENSO.DRM_RELATION_NM_PK ON DENSO.DNKR_RELATION_NM
(REL_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_RELATION_NM ADD (
  CONSTRAINT DNKR_RELATION_NM_PK
  PRIMARY KEY
  (REL_CODE)
  USING INDEX DENSO.DRM_RELATION_NM_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_RELATION_NM ADD (
  CONSTRAINT DNKR_RELATION_NM_FK1 
  FOREIGN KEY (CMC_CODE) 
  REFERENCES DENSO.DNKR_COMMON_CODE (CMC_CODE)
  ENABLE VALIDATE);