ALTER TABLE DENSO.DNKR_MENU_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_MENU_CODE CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_MENU_CODE
(
  MCD_CODE   NUMBER                             NOT NULL,
  MCD_USE    CHAR(1 BYTE)                       DEFAULT 'Y',
  MCD_SORT   NUMBER(5)                          DEFAULT 0,
  MCD_REF    NUMBER,
  MCD_URI    VARCHAR2(200 BYTE),
  MCD_DEPTH  NUMBER(3)                          DEFAULT 1
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_CODE IS '메뉴코드';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_USE IS '사용여부(Y,N)';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_SORT IS '정렬순서';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_REF IS '부모메뉴코드';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_URI IS '링크주소';

COMMENT ON COLUMN DENSO.DNKR_MENU_CODE.MCD_DEPTH IS '메뉴단계';


CREATE UNIQUE INDEX DENSO.DNKR_MENU_CODE_PK ON DENSO.DNKR_MENU_CODE
(MCD_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_MENU_CODE ADD (
  CONSTRAINT DNKR_MENU_CODE_PK
  PRIMARY KEY
  (MCD_CODE)
  USING INDEX DENSO.DNKR_MENU_CODE_PK
  ENABLE VALIDATE);