ALTER TABLE DENSO.DNKR_AUTH_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_AUTH_CODE CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_AUTH_CODE
(
  AUTH_CODE  VARCHAR2(45 BYTE)                  NOT NULL,
  AUTH_USE   CHAR(1 BYTE)                       DEFAULT 'Y'
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE.AUTH_CODE IS '권한코드';

COMMENT ON COLUMN DENSO.DNKR_AUTH_CODE.AUTH_USE IS '사용여부';


CREATE UNIQUE INDEX DENSO.DRM_AUTH_CODE_PK ON DENSO.DNKR_AUTH_CODE
(AUTH_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_AUTH_CODE ADD (
  CONSTRAINT DNKR_AUTH_CODE_PK
  PRIMARY KEY
  (AUTH_CODE)
  USING INDEX DENSO.DRM_AUTH_CODE_PK
  ENABLE VALIDATE);