ALTER TABLE DENSO.DNKR_SURVEY_ANSWER
 DROP PRIMARY KEY CASCADE;

DROP TABLE DENSO.DNKR_SURVEY_ANSWER CASCADE CONSTRAINTS;

CREATE TABLE DENSO.DNKR_SURVEY_ANSWER
(
  ASW_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  QST_CODE  VARCHAR2(45 BYTE)                   NOT NULL,
  SRV_CODE  VARCHAR2(45 BYTE)                   NOT NULL
)
TABLESPACE DRM
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN DENSO.DNKR_SURVEY_ANSWER.ASW_CODE IS '답변코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_ANSWER.QST_CODE IS '질문코드';

COMMENT ON COLUMN DENSO.DNKR_SURVEY_ANSWER.SRV_CODE IS '설문코드';


CREATE UNIQUE INDEX DENSO.DRM_SURVEY_ANSWER_PK ON DENSO.DNKR_SURVEY_ANSWER
(ASW_CODE)
LOGGING
TABLESPACE DRM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE DENSO.DNKR_SURVEY_ANSWER ADD (
  CONSTRAINT DNKR_SURVEY_ANSWER_PK
  PRIMARY KEY
  (ASW_CODE)
  USING INDEX DENSO.DRM_SURVEY_ANSWER_PK
  ENABLE VALIDATE);

ALTER TABLE DENSO.DNKR_SURVEY_ANSWER ADD (
  CONSTRAINT DNKR_SURVEY_ANSWER_FK1 
  FOREIGN KEY (SRV_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_CODE (SRV_CODE)
  ENABLE VALIDATE,
  CONSTRAINT DNKR_SURVEY_ANSWER_FK2 
  FOREIGN KEY (QST_CODE) 
  REFERENCES DENSO.DNKR_SURVEY_QUESTION (QST_CODE)
  ENABLE VALIDATE);